name: 'Application (PR)'
on:
  pull_request:
    branches:
      - main
    paths:
      - Application/**
defaults:
  run:
    shell: bash
    working-directory: 'Application'
env:
  configuration: Release
  coverage_report_path: '${{ github.workspace }}/coverage'
  verbosity: normal
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Clean workspace'
      run: dotnet clean --configuration ${{ env.configuration }} --nologo --verbosity ${{ env.verbosity }} *.sln
    - name: 'Restore nuget packages'
      run: dotnet restore --nologo --verbosity ${{ env.verbosity }} *.sln
    - name: 'Build visual studio solution'
      run: dotnet build --configuration ${{ env.configuration }} --nologo --no-restore --verbosity ${{ env.verbosity }} *.sln
    - name: 'Run unit tests'
      run: dotnet test --collect:'XPlat Code Coverage' --configuration ${{ env.configuration }} --no-build --nologo --results-directory ${{ env.coverage_report_path }} --verbosity ${{ env.verbosity }} *.sln
