name: 'Application (Release)'
on:
  workflow_run:
    workflows:
      - 'Application (Build)'
    types:
      - completed
defaults:
  run:
    shell: bash
    working-directory: 'Application'
env:
  github_feed_url: https://nuget.pkg.github.com/josemaria-toro/index.json
  packages_output_path: '${{ github.workspace }}/packages'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: 'Application.Packages'
        path: ${{ env.packages_output_path }}
    - name: 'Publish nuget packages'
      run: dotnet nuget push ${{ env.packages_output_path }}/*.nupkg --api-key ${{ secrets.FEED_TOKEN }} --skip-duplicate --source ${{ env.github_feed_url }}
