name: .NET Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: build_vs_solution
    description: Build Visual Studio Solution
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      description: Checkout the source code
      uses: actions/checkout@v4
    - name: dotnet_setup
      description: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: restore
      description: Restore dependencies
      run: dotnet restore Zetatech.Accelerate.sln --nologo --verbosity minimal
    - name: cleanup
      description: Clean workspace
      run: dotnet clean Zetatech.Accelerate.sln --configuration release --nologo --verbosity minimal
    - name: build
      description: Build solution
      run: dotnet build Zetatech.Accelerate.sln --configuration release --no-incremental --no-restore --nologo